name: Codecov
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install modules
      run: |
        npm i
    - name: Generate coverage report
      run: |
        npx nyc report --reporter=text-lcov | npx coveralls
        npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/lcov-report/
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
