name: Codecov
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install modules
      run: |
        npm i
        npm i codecov coveralls
        nyc report --reporter=text-lcov | coveralls
        nyc report --reporter=text-lcov > coverage.lcov && codecov
    - name: Generate coverage report
      run: |
        nyc report --reporter=text-lcov | coveralls
        nyc report --reporter=text-lcov > coverage.lcov && codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/lcov-report/
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
